/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'account-security': RouteRecordInfo<'account-security', '/account/security', Record<never, never>, Record<never, never>>,
    'admin-permissions': RouteRecordInfo<'admin-permissions', '/admin/permissions', Record<never, never>, Record<never, never>>,
    'admin-roles': RouteRecordInfo<'admin-roles', '/admin/roles', Record<never, never>, Record<never, never>>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'capacite-emprunt': RouteRecordInfo<'capacite-emprunt', '/capacite-emprunt', Record<never, never>, Record<never, never>>,
    'comparateur': RouteRecordInfo<'comparateur', '/comparateur', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'mes-simulations': RouteRecordInfo<'mes-simulations', '/mes-simulations', Record<never, never>, Record<never, never>>,
    'mes-simulations-id': RouteRecordInfo<'mes-simulations-id', '/mes-simulations/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'remboursement-anticipe': RouteRecordInfo<'remboursement-anticipe', '/remboursement-anticipe', Record<never, never>, Record<never, never>>,
    'stoken': RouteRecordInfo<'stoken', '/s/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'simulateur': RouteRecordInfo<'simulateur', '/simulateur', Record<never, never>, Record<never, never>>,
  }
}
